### ISSUE TITLE
Wikidata auto select error (3.6.0)

### ISSUE THREAD

**Issue by jdlrobson** [jdlrobson/Gadget-Workshop#12]
* Visit https://it.wikivoyage.org/wiki/Utente:Jdlrobson/sandbox
* Click first edit icon
* Add Hotel Ánfora in the Wikidata field
* Click " Sync shared fields to/from Wikidata"
* Get `ext.gadget.ListingEditorMain-script-0.js:2564 Uncaught TypeError: Cannot read properties of undefined (reading 'id')` 
```
ext.gadget.ListingEditorMain-script-0.js:2564 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at createRadio (ext.gadget.ListingEditorMain-script-0.js:2564:76)
    at Object.ajaxSuccess [as success] (ext.gadget.ListingEditorMain-script-0.js:2471:18)
    at fire (jquery.js:3223:31)
    at Object.fireWith [as resolveWith] (jquery.js:3353:7)
    at done (jquery.js:9627:14)
    at HTMLScriptElement.callback (jquery.js:10011:8)
    at HTMLScriptElement.dispatch (jquery.js:5145:27)
    at HTMLScriptElement.<anonymous> (jquery.js:4949:28)
```

**Comment by jdlrobson** [comment]
Likely an issue with the parser.

**Comment by jdlrobson** [comment]
https://phabricator.wikimedia.org/T381786
